alias l='clear'
alias x='exit'
alias i='sudo -i'
alias ll='ls -lh'
alias la='ls -lah'
alias lv='lsblk'
alias chmod='chmod -R'
alias chown='chown -R'
alias cp='cp -av'
alias rm='sudo rm -rf'
alias xrr='xrandr --output eDP1 --mode 3200x1800 --dpi 220'
alias xalias='vim ${HOME}/.bash.d/.bash_aliases'
alias xapt='sudo vim /etc/apt/sources.list'
alias xnet='sudo vim /etc/network/interfaces'
alias xcon='sudo dpkg-reconfigure console-setup'
alias mount='sudo mount'
alias apt-get='sudo apt-get'
alias ssh='TERM=xterm ssh -p 220'
alias delta='TERM=xterm ssh -p 220 lorin@ts.loginto.me'
alias sigma='TERM=xterm ssh -p 221 loki@ts.loginto.me'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade -y'
alias dist-upgrade='sudo apt-get dist-upgrade -y'
alias install='sudo apt-get -y install'
alias remove='sudo apt-get remove --purge -y'
alias clean='sudo apt-get autoremove -y && sudo apt-get autoclean -y'
alias cache='apt-cache search'
alias i3blockcfg='vim ${HOME}/.config/i3blocks/config'
alias xii='vim ${HOME}/.i3/config'
alias i3lockcfg='vim ${HOME}/.config/i3lock.sh'
alias trellis='git clone --depth=1 https://github.com/roots/trellis.git && rm -rf trellis/.git && cd trellis && ansible-galaxy install -r requirements.yml && cd ..'
alias bedrock='git clone --depth=1 https://github.com/roots/bedrock.git site && rm -rf site/.git && cd site && composer install'
alias sage='composer create-project roots/sage web/app/themes/affinityskin'
alias soil='composer require roots/soil 3.7.0'
alias roots='git clone --depth=1 https://github.com/roots/trellis.git && rm -rf trellis/.git && git clone --depth=1 https://github.com/roots/bedrock.git site && rm -rf site/.git && cd site && composer install && mkdir web/app/themes/affinityskin && composer create-project roots/sage web/app/themes/affinityskin && cd web/app/themes/affinityskin && npm install && bower install && gulp && cd ../../../../ && composer require roots/soil 3.7.0'
alias drivemount='sudo mount /dev/sda4 /mnt'
